version: "3.8"

services:

  backend:
    build: .
    container_name: ollama-backend
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/backend/data

    restart: unless-stopped

volumes:
  backend_data: