version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: SRHR_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: .
    container_name: ollama-backend
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - backend_data:/backend/data
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  backend_data: